# Generated by Django 2.2.4 on 2019-08-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=200)),
                ('user_connections', models.ManyToManyField(related_name='related_to', through='users.Connection', to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_users', to='users.User'),
        ),
        migrations.AddField(
            model_name='connection',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_users', to='users.User'),
        ),
    ]
